### ISSUE TITLE
Implement similar shows

### ISSUE THREAD

**Issue by c0de-wizard** [c0de-wizard/tv-maniac#19]
Load similar movies after navigating to Show details.

**Comment by Shlok1999** [comment]
I would like to work on this issue. Please grant me the access

**Comment by c0de-wizard** [comment]
Hi @Shlok1999 . Thanks for wanting to contribute. Feel free to fork the project and create a PR once done. Side note: A lot is changing in the project right now but this should not stop you from working on it. 😎
